
# backend-config.yaml only applies for GCP

apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: ml-api-backend-config
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /health
    port: 8080
  connectionDraining:
    drainingTimeoutSec: 60
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 1800  # 30 minutes
  timeoutSec: 30  # Request timeout
  logging:
    enable: true
    sampleRate: 1.0  # Log all requests for production