apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-api-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/sagemaker-end-to-end-deployment.git
    targetRevision: develop
    path: deploy/kubernetes/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true