# security/rbac/rbac.yaml
# Example Kubernetes RBAC configuration
# Adapt this to your specific needs

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: training-pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: training-pod-reader-binding
subjects:
- kind: ServiceAccount
  name: training-service-account #  Make sure this service account exists
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: training-pod-reader