groups:
  - name: api_alerts
    rules:
      - alert: APIHighLatency
        expr: histogram_quantile(0.95, sum(rate(api_prediction_latency_seconds_bucket[5m]))) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "API latency is high (95th percentile is above 0.5 seconds)"
          description: "The API is experiencing high latency. Investigate the root cause immediately."

      - alert: APIErrorRateHigh
        expr: sum(rate(prediction_errors_total[5m])) / sum(rate(prediction_requests_total[5m])) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "API error rate is high (greater than 5%)"
          description: "The API is experiencing a high error rate. Investigate the root cause immediately."

      - alert: APIRequestsMissing
        expr: time() - api_http_requests_total offset 5m < 5
        for: 5m
        labels:
          severity: warning
        annotations:
            summary: No Requests Recieved.
            description: No Requests Recieved in the past 5 minutes. -  This may be a service error.