apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/load-balancer
namespace: prod
namePrefix: prod-
commonAnnotations:
  environment: prod
  cloud: gcp
patchesStrategicMerge:
  - backend-config.yaml  # GCP-specific backend config