apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/load-balancer
namespace: dev

namePrefix: dev-

commonAnnotations:
  environment: dev
  cloud: gcp

patchesStrategicMerge:
  - backend-config.yaml