{
 "title": "API Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(rate(ml_api_http_requests_total[5m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "content": "{{ .values.error_rate }}" },
   "targets": [
    {
     "dedupStrategy": "avg",
     "expr": "sum(rate(ml_api_http_requests_errors_total[5m])) / sum(rate(ml_api_http_requests_total[5m])) * 100"
    }
   ]
  },
  {
   "title": "95th Percentile Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(api_prediction_latency_seconds_bucket[5m]))) * 1000"
    }
   ]
  }
 ]
}